CREATE TABLE book (
   id bigint auto_increment,
   name VARCHAR(100) NOT NULL
);
insert into book (name) values ('ULYSSES');
insert into book (name) values ('THE GREAT GATSBY');
insert into book (name) values ('A PORTRAIT OF THE ARTIST AS A YOUNG MAN');
insert into book (name) values ('LOLITA');
insert into book (name) values ('BRAVE NEW WORLD');
insert into book (name) values ('THE SOUND AND THE FURY');
insert into book (name) values ('CATCH-22');
insert into book (name) values ('DARKNESS AT NOON');
insert into book (name) values ('SONS AND LOVERS');
insert into book (name) values ('THE GRAPES OF WRATH');
insert into book (name) values ('UNDER THE VOLCANO');
insert into book (name) values ('THE WAY OF ALL FLESH');
insert into book (name) values ('1984');
insert into book (name) values ('I, CLAUDIUS');
insert into book (name) values ('TO THE LIGHTHOUSE');
insert into book (name) values ('AN AMERICAN TRAGEDY');
insert into book (name) values ('THE HEART IS A LONELY HUNTER');
insert into book (name) values ('SLAUGHTERHOUSE-FIVE');
insert into book (name) values ('INVISIBLE MAN');
insert into book (name) values ('NATIVE SON');
insert into book (name) values ('HENDERSON THE RAIN KING');
insert into book (name) values ('APPOINTMENT IN SAMARRA');
insert into book (name) values ('U.S.A.(trilogy)');
insert into book (name) values ('WINESBURG, OHIO');
insert into book (name) values ('A PASSAGE TO INDIA');
insert into book (name) values ('THE WINGS OF THE DOVE');
insert into book (name) values ('THE AMBASSADORS');
insert into book (name) values ('TENDER IS THE NIGHT');
insert into book (name) values ('THE STUDS LONIGAN TRILOGY');
insert into book (name) values ('THE GOOD SOLDIER');
insert into book (name) values ('ANIMAL FARM');
insert into book (name) values ('THE GOLDEN BOWL');
insert into book (name) values ('SISTER CARRIE');
insert into book (name) values ('A HANDFUL OF DUST');
insert into book (name) values ('AS I LAY DYING');
insert into book (name) values ('ALL THE KING’S MEN');
insert into book (name) values ('THE BRIDGE OF SAN LUIS REY');
insert into book (name) values ('HOWARDS END');
insert into book (name) values ('GO TELL IT ON THE MOUNTAIN');
insert into book (name) values ('THE HEART OF THE MATTER');
insert into book (name) values ('LORD OF THE FLIES');
insert into book (name) values ('DELIVERANCE');
insert into book (name) values ('A DANCE TO THE MUSIC OF TIME (series)');
insert into book (name) values ('POINT COUNTER POINT');
insert into book (name) values ('THE SUN ALSO RISES');
insert into book (name) values ('THE SECRET AGENT');
insert into book (name) values ('NOSTROMO');
insert into book (name) values ('THE RAINBOW');
insert into book (name) values ('WOMEN IN LOVE');
insert into book (name) values ('TROPIC OF CANCER');
insert into book (name) values ('THE NAKED AND THE DEAD');
insert into book (name) values ('PORTNOY’S COMPLAINT');
insert into book (name) values ('PALE FIRE');
insert into book (name) values ('LIGHT IN AUGUST');
insert into book (name) values ('ON THE ROAD');
insert into book (name) values ('THE MALTESE FALCON');
insert into book (name) values ('PARADE’S END');
insert into book (name) values ('THE AGE OF INNOCENCE');
insert into book (name) values ('ZULEIKA DOBSON');
insert into book (name) values ('THE MOVIEGOER');
insert into book (name) values ('DEATH COMES FOR THE ARCHBISHOP');
insert into book (name) values ('FROM HERE TO ETERNITY');
insert into book (name) values ('THE WAPSHOT CHRONICLES');
insert into book (name) values ('THE CATCHER IN THE RYE');
insert into book (name) values ('A CLOCKWORK ORANGE');
insert into book (name) values ('OF HUMAN BONDAGE');
insert into book (name) values ('HEART OF DARKNESS');
insert into book (name) values ('MAIN STREET');
insert into book (name) values ('THE HOUSE OF MIRTH');
insert into book (name) values ('THE ALEXANDRIA QUARTET');
insert into book (name) values ('A HIGH WIND IN JAMAICA');
insert into book (name) values ('A HOUSE FOR MR BISWAS');
insert into book (name) values ('THE DAY OF THE LOCUST');
insert into book (name) values ('A FAREWELL TO ARMS');
insert into book (name) values ('SCOOP');
insert into book (name) values ('THE PRIME OF MISS JEAN BRODIE');
insert into book (name) values ('FINNEGANS WAKE');
insert into book (name) values ('KIM');
insert into book (name) values ('A ROOM WITH A VIEW');
insert into book (name) values ('THE ADVENTURES OF AUGIE MARCH');
insert into book (name) values ('ANGLE OF REPOSE');
insert into book (name) values ('A BEND IN THE RIVER');
insert into book (name) values ('THE DEATH OF THE HEART');
insert into book (name) values ('LORD JAMAICA');
insert into book (name) values ('RAGTIME');
insert into book (name) values ('THE OLD WIVES’ TALE');
insert into book (name) values ('THE CALL OF THE WILD');
insert into book (name) values ('LOVING');
insert into book (name) values ('MIDNIGHT’S CHILDREN');
insert into book (name) values ('TOBACCO ROAD');
insert into book (name) values ('IRONWEED');
insert into book (name) values ('THE MAGUS');
insert into book (name) values ('WIDE SARGASSO SEA');
insert into book (name) values ('UNDER THE NET');
insert into book (name) values ('SOPHIE’S CHOICE');
insert into book (name) values ('THE SHELTERING SKY');
insert into book (name) values ('THE GINGER MAN');
insert into book (name) values ('THE MAGNIFICENT AMBERSONS');
